services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: relaforg
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pioche
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data

volumes:
  pgdata:
