//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::QuestionKind;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "answers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub participant_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub question: QuestionKind,
    pub value: String,
    #[sea_orm(
        belongs_to,
        from = "participant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub participants: BelongsTo<super::participants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
