//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::DrawKind;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "draws")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner_id: i32,
    pub kind: DrawKind,
    pub name: String,
    #[sea_orm(unique)]
    pub share_token: Option<String>,
    pub drawn_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub draw_questions: HasMany<super::draw_questions::Entity>,
    #[sea_orm(has_many)]
    pub participants: HasMany<super::participants::Entity>,
    #[sea_orm(has_one)]
    pub santa_settings: HasOne<super::santa_settings::Entity>,
    #[sea_orm(has_one)]
    pub team_settings: HasOne<super::team_settings::Entity>,
    #[sea_orm(has_many)]
    pub teams: HasMany<super::teams::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
