//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "participants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "name")]
    pub draw_id: i32,
    #[sea_orm(unique_key = "name")]
    pub name: String,
    #[sea_orm(unique)]
    pub access_token: Option<String>,
    pub form_completed_at: Option<DateTimeWithTimeZone>,
    pub team_id: Option<i32>,
    pub is_captain: bool,
    #[sea_orm(has_many)]
    pub answers: HasMany<super::answers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "draw_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub draws: BelongsTo<super::draws::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub teams: BelongsTo<Option<super::teams::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
