//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "santa_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub draw_id: i32,
    pub budget_cents: Option<i32>,
    pub exchange_date: Option<Date>,
    #[sea_orm(
        belongs_to,
        from = "draw_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub draws: BelongsTo<super::draws::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
