//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "santa_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub giver_id: i32,
    #[sea_orm(unique)]
    pub receiver_id: i32,
    #[sea_orm(
        belongs_to,
        relation_enum = "Participants2",
        from = "giver_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub participants_2: BelongsTo<super::participants::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Participants1",
        from = "receiver_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub participants_1: BelongsTo<super::participants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
