//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "draw_kind")]
pub enum DrawKind {
    #[sea_orm(string_value = "secret_santa")]
    SecretSanta,
    #[sea_orm(string_value = "teams")]
    Teams,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "question_kind")]
pub enum QuestionKind {
    #[sea_orm(string_value = "tshirt_size")]
    TshirtSize,
    #[sea_orm(string_value = "shoe_size")]
    ShoeSize,
    #[sea_orm(string_value = "allergies")]
    Allergies,
    #[sea_orm(string_value = "wishes")]
    Wishes,
    #[sea_orm(string_value = "dislikes")]
    Dislikes,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "team_mode")]
pub enum TeamMode {
    #[sea_orm(string_value = "size")]
    Size,
    #[sea_orm(string_value = "count")]
    Count,
}
