//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TeamMode;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "team_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub draw_id: i32,
    pub mode: TeamMode,
    pub value: i16,
    pub has_captain: bool,
    pub allow_unequal: bool,
    pub allow_redraw: bool,
    #[sea_orm(
        belongs_to,
        from = "draw_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub draws: BelongsTo<super::draws::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
