//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub draw_id: i32,
    pub name: String,
    pub position: i16,
    #[sea_orm(
        belongs_to,
        from = "draw_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub draws: BelongsTo<super::draws::Entity>,
    #[sea_orm(has_many)]
    pub participants: HasMany<super::participants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
