//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub password_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
